# Generated by Django 4.2.1 on 2023-07-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollstudent', '0002_remove_user_password_user_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='StudentModel',
        ),
    ]
